[package]
name = "afastdata-macro"
version.workspace = true
edition.workspace = true
authors = ["ahriknow <ahriknow@ahriknow.com>"]
description = "Derive macros for afastdata serialization and deserialization"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/ahriknow/afastdata"
homepage = "https://github.com/ahriknow/afastdata"
documentation = "https://docs.rs/afastdata-macro"
keywords = ["serialization", "binary", "derive", "macro"]
categories = ["encoding"]
exclude = ["tests/"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"

[features]
default = ["tag-u8"]
tag-u8 = []
tag-u16 = []
tag-u32 = []

[dev-dependencies]
afastdata = { path = "../afastdata" }
