[package]
name = "afastdata-core"
version.workspace = true
edition.workspace = true
authors = ["ahriknow <ahriknow@ahriknow.com>"]
description = "Core traits and built-in type implementations for afastdata serialization"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/ahriknow/afastdata"
homepage = "https://github.com/ahriknow/afastdata"
documentation = "https://docs.rs/afastdata-core"
keywords = ["serialization", "binary", "no-std"]
categories = ["encoding", "no-std"]

[features]
default = []
len-u64 = []

[dev-dependencies]
afastdata-macro = { workspace = true }
